services:
  api:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI=${MONGO_URI}
      
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
     - mongodb_data:/data/bloggingapp

volumes:
  mongodb_data:
